version: "3.4"

services:
  kafka:
    image: docker.io/bitnami/kafka:3.5
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_RAFT_CLUSTER_ID=LOCALHOST
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:29093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # Settings
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

  mongo:
    image: mongo:7.0.0
    hostname: mongodb
    container_name: mongo-db    
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - "mongo_data:/data/db"

  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    hostname: sqlserver
    container_name: sql-server-db
    ports:
      - "1433:1433"
    volumes:
      - "sqlserver_data:/var/opt/mssql"
    environment:
      SA_PASSWORD: "FA22lFI9gRpUzfe"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"

  kafka-ui:
    image: provectuslabs/kafka-ui:b0583a3ca7d58bd9978e26a67bb8927fcbf03c42
    hostname: kafkaui
    container_name: kafka-ui    
    ports:
      - 8080:8080
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: socialmedia
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

  kafka-startup-setup:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka-startup-setup
    depends_on:
      - kafka
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
               cub kafka-ready -b kafka:29092 1 30 && \
               kafka-topics --create --topic sample_topic --partitions 3 --replication-factor 1 --if-not-exists --bootstrap-server kafka:29092 && \
               kafka-topics --create --topic sm_post_events --partitions 3 --replication-factor 1 --if-not-exists --bootstrap-server kafka:29092'"

volumes:
  kafka_data:
    driver: local
  mongo_data:
    driver: local
  sqlserver_data:
    driver: local
   
networks:
  bridge:
    external: true
